"""init

Revision ID: 21aac518027b
Revises: f9f79f458f95
Create Date: 2026-01-02 10:34:04.210025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21aac518027b'
down_revision: Union[str, Sequence[str], None] = 'f9f79f458f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_role', 'data_scope',
               existing_type=mysql.SMALLINT(),
               type_=sa.Enum('ALL', 'DEPT_AND_CHILD', 'DEPT', 'SELF', name='roledatascope'),
               comment='数据范围',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_role', 'data_scope',
               existing_type=sa.Enum('ALL', 'DEPT_AND_CHILD', 'DEPT', 'SELF', name='roledatascope'),
               type_=mysql.SMALLINT(),
               comment=None,
               existing_comment='数据范围',
               existing_nullable=True)
    # ### end Alembic commands ###
