"""init

Revision ID: 426b6afca259
Revises: f747767d6042
Create Date: 2025-12-28 15:48:22.673680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426b6afca259'
down_revision: Union[str, Sequence[str], None] = 'f747767d6042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'))
    op.add_column('items', sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'))
    op.add_column('items', sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'))
    op.add_column('items', sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'))
    op.add_column('items', sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'))
    op.add_column('items', sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'))
    op.add_column('items', sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'remark')
    op.drop_column('items', 'delete_by')
    op.drop_column('items', 'update_by')
    op.drop_column('items', 'create_by')
    op.drop_column('items', 'delete_time')
    op.drop_column('items', 'update_time')
    op.drop_column('items', 'create_time')
    # ### end Alembic commands ###
