"""add is_deleted

Revision ID: 6da0b6426d3d
Revises: 921a3144fb19
Create Date: 2026-01-06 18:06:52.582235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da0b6426d3d'
down_revision: Union[str, Sequence[str], None] = '921a3144fb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_dept', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_dict', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_dict_item', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_menu', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_notice', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_role', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_role_menu', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_user', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('sys_user_notice', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    op.add_column('user_role_ref', sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role_ref', 'is_deleted')
    op.drop_column('sys_user_notice', 'is_deleted')
    op.drop_column('sys_user', 'is_deleted')
    op.drop_column('sys_role_menu', 'is_deleted')
    op.drop_column('sys_role', 'is_deleted')
    op.drop_column('sys_notice', 'is_deleted')
    op.drop_column('sys_menu', 'is_deleted')
    op.drop_column('sys_dict_item', 'is_deleted')
    op.drop_column('sys_dict', 'is_deleted')
    op.drop_column('sys_dept', 'is_deleted')
    op.drop_column('items', 'is_deleted')
    # ### end Alembic commands ###
