"""add sys_config table

Revision ID: d48ed8269a9f
Revises: 6da0b6426d3d
Create Date: 2026-01-08 10:49:05.222944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48ed8269a9f'
down_revision: Union[str, Sequence[str], None] = '6da0b6426d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_config',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('type', sa.Enum('STRING', 'NUMBER', 'LIST', 'DICT', name='configtypeenum'), nullable=False, comment='配置类型'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_config_id'), 'sys_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_config_id'), table_name='sys_config')
    op.drop_table('sys_config')
    # ### end Alembic commands ###
