"""Add sys_notice and sys_user_notice tables

Revision ID: e5b51fe78dcf
Revises: d1958092023e
Create Date: 2026-01-02 11:44:05.795534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b51fe78dcf'
down_revision: Union[str, Sequence[str], None] = 'd1958092023e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user_notice',
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id', 'user_id')
    )
    op.create_index(op.f('ix_sys_user_notice_id'), 'sys_user_notice', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_notice_id'), table_name='sys_user_notice')
    op.drop_table('sys_user_notice')
    # ### end Alembic commands ###
