"""init

Revision ID: f9f79f458f95
Revises: 
Create Date: 2026-01-02 10:31:06.559728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f79f458f95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_table('sys_dept',
    sa.Column('name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='部门编号'),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='父节点id'),
    sa.Column('tree_path', sa.String(length=255), nullable=False, comment='父节点路径'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='显示顺序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态(1-正常 0-禁用)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sys_dept_id'), 'sys_dept', ['id'], unique=False)
    op.create_index('uk_code', 'sys_dept', ['code'], unique=True, mysql_length=100)
    op.create_table('sys_dict',
    sa.Column('code', sa.String(length=50), nullable=True, comment='类型编码'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='类型名称'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态(0:正常;1:禁用)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_dict_code'), 'sys_dict', ['code'], unique=False)
    op.create_index(op.f('ix_sys_dict_id'), 'sys_dict', ['id'], unique=False)
    op.create_table('sys_dict_item',
    sa.Column('dict_code', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('tag_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_dict_item_id'), 'sys_dict_item', ['id'], unique=False)
    op.create_table('sys_menu',
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='父菜单ID'),
    sa.Column('tree_path', sa.String(length=255), nullable=True, comment='父节点ID路径'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='菜单名称'),
    sa.Column('type', sa.Enum('CATALOG', 'MENU', 'BUTTON', 'EXTLINK', name='menutype'), nullable=False, comment='菜单类型'),
    sa.Column('route_name', sa.String(length=255), nullable=True),
    sa.Column('route_path', sa.String(length=128), nullable=True),
    sa.Column('component', sa.String(length=128), nullable=True),
    sa.Column('perm', sa.String(length=128), nullable=True),
    sa.Column('always_show', sa.SmallInteger(), nullable=True),
    sa.Column('keep_alive', sa.SmallInteger(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('redirect', sa.String(length=128), nullable=True),
    sa.Column('params', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_menu_id'), 'sys_menu', ['id'], unique=False)
    op.create_table('sys_role',
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='角色编码'),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='角色状态'),
    sa.Column('data_scope', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=False)
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'menu_id')
    )
    op.create_index(op.f('ix_sys_role_menu_id'), 'sys_role_menu', ['id'], unique=False)
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=64), nullable=True, comment='用户名'),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='性别'),
    sa.Column('hashed_password', sa.String(length=100), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('openid', sa.String(length=28), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级管理员'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活动状态'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=False)
    op.create_table('user_role_ref',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='uid'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='uid'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('create_by', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=255), nullable=True, comment='更新者'),
    sa.Column('delete_by', sa.String(length=255), nullable=True, comment='删除者'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_role_ref_id'), 'user_role_ref', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_ref_id'), table_name='user_role_ref')
    op.drop_table('user_role_ref')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_menu_id'), table_name='sys_role_menu')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_menu_id'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_dict_item_id'), table_name='sys_dict_item')
    op.drop_table('sys_dict_item')
    op.drop_index(op.f('ix_sys_dict_id'), table_name='sys_dict')
    op.drop_index(op.f('ix_sys_dict_code'), table_name='sys_dict')
    op.drop_table('sys_dict')
    op.drop_index('uk_code', table_name='sys_dept', mysql_length=100)
    op.drop_index(op.f('ix_sys_dept_id'), table_name='sys_dept')
    op.drop_table('sys_dept')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
