from enum import Enum


class ErrorCode(str, Enum):
    # Success
    SUCCESS = "SUCCESS"

    # Common
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    NOT_FOUND = "NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    OPERATION_FAILED = "OPERATION_FAILED"

    # User
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PASSWORD_MISMATCH = "PASSWORD_MISMATCH"

    # Role
    ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"

    # Dept
    DEPT_ALREADY_EXISTS = "DEPT_ALREADY_EXISTS"
    DEPT_NOT_FOUND = "DEPT_NOT_FOUND"
    PARENT_DEPT_NOT_FOUND = "PARENT_DEPT_NOT_FOUND"
    PARENT_DEPT_DISABLED = "PARENT_DEPT_DISABLED"

    # Menu
    MENU_NOT_FOUND = "MENU_NOT_FOUND"
    PARENT_MENU_NOT_FOUND = "PARENT_MENU_NOT_FOUND"

    # Dict
    DICT_ALREADY_EXISTS = "DICT_ALREADY_EXISTS"
    DICT_NOT_FOUND = "DICT_NOT_FOUND"
    DICT_ITEM_NOT_FOUND = "DICT_ITEM_NOT_FOUND"

    # Config
    CONFIG_KEY_EXISTS = "CONFIG_KEY_EXISTS"
    CONFIG_NAME_EXISTS = "CONFIG_NAME_EXISTS"
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"

    # Notice
    NOTICE_NOT_FOUND = "NOTICE_NOT_FOUND"
